### ISSUE TITLE
app.py:225: RuntimeWarning: invalid value encountered in cast

### ISSUE THREAD

**Issue by petermg** [zhyever/PatchFusion#15]
When changing the resolution, for example from from 540 x 960 to 512 x 512, so far this happens with any other resolution I set it to, I get the following error:
app.py:225: RuntimeWarning: invalid value encountered in cast

**Comment by zhyever** [comment]
Thanks for your interest in our work. This issue is caused by unconvered area. In another word, if you are using P16 mode with image resolution 4k, and at the same time you try to use patch size 512x512, there will be some areas not be convered by P16 patches, leading to invalid number in local ensemble
